#global config
global:
  scrape_interval:     15s
  evaluation_interval: 5s

rule_files:
  - "/etc/prometheus/alerts.yml"

# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'Fast-api'
    scrape_interval: 5s
    static_configs:
      - targets: [host.docker.internal:5000]